%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.4.1

-ifndef(concentrate_pb).
-define(concentrate_pb, true).

-define(concentrate_pb_gpb_version, "4.4.1").

-ifndef('MINER_RXPACKET_PB_PB_H').
-define('MINER_RXPACKET_PB_PB_H', true).
-record(miner_RxPacket_pb,
        {freq = 0               :: non_neg_integer() | undefined, % = 1, 32 bits
         if_chain = 0           :: non_neg_integer() | undefined, % = 2, 32 bits
         crc_check = false      :: boolean() | 0 | 1 | undefined, % = 3
         timestamp = 0          :: non_neg_integer() | undefined, % = 4, 32 bits
         radio = 'R0'           :: 'R0' | 'R1' | integer() | undefined, % = 5, enum Radio
         bandwidth = 'UNDEFINED' :: 'UNDEFINED' | 'BW7_8kHz' | 'BW15_6kHz' | 'BW31_2kHz' | 'BW62_5kHz' | 'BW125kHz' | 'BW250kHz' | 'BW500kHz' | integer() | undefined, % = 6, enum Bandwidth
         spreading = 'UNDEFINED' :: 'UNDEFINED' | 'SF7' | 'SF8' | 'SF9' | 'SF10' | 'SF11' | 'SF12' | integer() | undefined, % = 7, enum Spreading
         coderate = 'UNDEFINED' :: 'UNDEFINED' | 'CR4_5' | 'CR4_6' | 'CR4_7' | 'CR4_8' | integer() | undefined, % = 8, enum Coderate
         rssi = 0.0             :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 9
         snr = 0.0              :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 10
         payload = <<>>         :: iodata() | undefined % = 11
        }).
-endif.

-ifndef('MINER_TXPACKET_PB_PB_H').
-define('MINER_TXPACKET_PB_PB_H', true).
-record(miner_TxPacket_pb,
        {freq = 0               :: non_neg_integer() | undefined, % = 1, 32 bits
         radio = 'R0'           :: 'R0' | 'R1' | integer() | undefined, % = 2, enum Radio
         power = 0              :: integer() | undefined, % = 3, 32 bits
         bandwidth = 'UNDEFINED' :: 'UNDEFINED' | 'BW7_8kHz' | 'BW15_6kHz' | 'BW31_2kHz' | 'BW62_5kHz' | 'BW125kHz' | 'BW250kHz' | 'BW500kHz' | integer() | undefined, % = 4, enum Bandwidth
         spreading = 'UNDEFINED' :: 'UNDEFINED' | 'SF7' | 'SF8' | 'SF9' | 'SF10' | 'SF11' | 'SF12' | integer() | undefined, % = 5, enum Spreading
         coderate = 'UNDEFINED' :: 'UNDEFINED' | 'CR4_5' | 'CR4_6' | 'CR4_7' | 'CR4_8' | integer() | undefined, % = 6, enum Coderate
         invert_polarity = false :: boolean() | 0 | 1 | undefined, % = 7
         omit_crc = false       :: boolean() | 0 | 1 | undefined, % = 8
         implicit_header = false :: boolean() | 0 | 1 | undefined, % = 9
         payload = <<>>         :: iodata() | undefined % = 10
        }).
-endif.

-endif.
