steps:
  - commands:
      - "make compile"
      - "make ci"
    name: ":hammer: build"
    key: "tests"
    agents:
      queue: "erlang"
    artifact_paths:
      - "artifacts/*"

  - if: build.tag =~ /^seed/
    name: ":debian: build seed deb"
    commands:
      - "git fetch -t"
      - ".buildkite/scripts/make_deb.sh seed"
    key: "seed-deb"
    artifact_paths: "*.deb"
    agents:
      queue: "erlang"

  - if: build.tag =~ /^testnet_seed/
    name: ":debian: build testnet seed deb"
    commands:
      - "git fetch -t"
      - ".buildkite/scripts/make_deb.sh testnet_seed"
    key: "testnet-seed-deb"
    artifact_paths: "*.deb"
    agents:
      queue: "erlang"

  - if: build.tag =~ /^validator/
    name: ":debian: build validator deb"
    commands:
      - "git fetch -t"
      - ".buildkite/scripts/make_deb.sh validator"
    key: "val-deb"
    artifact_paths: "*.deb"
    agents:
      queue: "erlang"

  - if: build.tag =~ /^seed/
    name: ":cloud: upload seed deb to packagecloud"
    commands:
      - "git fetch -t"
      - ".buildkite/scripts/packagecloud_upload.sh seed"
    depends_on: "seed-deb"
    agents:
      queue: "erlang"

  - if: build.tag =~ /^testnet_seed/
    name: ":cloud: upload testnet seed deb to packagecloud"
    commands:
      - "git fetch -t"
      - ".buildkite/scripts/packagecloud_upload.sh testnet_seed"
    depends_on: "testnet-seed-deb"
    agents:
      queue: "erlang"

  - if: build.tag =~ /^validator/
    name: ":cloud: upload validator deb to packagecloud"
    commands:
      - "git fetch -t"
      - ".buildkite/scripts/packagecloud_upload.sh validator"
    depends_on: "val-deb"
    agents:
      queue: "erlang"

  - if: build.tag =~ /^validator/
    name: "validator AMD64 docker"
    env:
      REGISTRY_HOST: "quay.io"
      REGISTRY_NAME: "validator"
      IMAGE_ARCH: "amd64"
      BUILD_TYPE: "validator"
    agents:
      queue: "erlang"
    commands:
      - "git fetch -t"
      - ".buildkite/scripts/make_image.sh"

  - if: build.tag =~ /^validator/
    name: "validator ARM64 docker"
    env:
      REGISTRY_HOST: "quay.io"
      REGISTRY_NAME: "validator"
      IMAGE_ARCH: "arm64"
      BUILD_TYPE: "validator"
    agents:
      queue: "arm64"
    commands:
      - "git fetch -t"
      - ".buildkite/scripts/make_image.sh"

  - if: build.tag =~ /^val\d/
    name: "testnet validator AMD64 docker"
    env:
      REGISTRY_HOST: "quay.io"
      REGISTRY_NAME: "validator"
      IMAGE_ARCH: "amd64"
      BUILD_TYPE: "val"
    agents:
      queue: "erlang"
    commands:
      - "git fetch -t"
      - ".buildkite/scripts/make_image.sh"

  - if: build.tag =~ /^val\d/
    name: "testnet validator ARM64 docker"
    env:
      REGISTRY_HOST: "quay.io"
      REGISTRY_NAME: "validator"
      IMAGE_ARCH: "arm64"
      BUILD_TYPE: "val"
    agents:
      queue: "arm64"
    commands:
      - "git fetch -t"
      - ".buildkite/scripts/make_image.sh"

  - if: build.tag != null && build.tag !~ /^validator/ && build.tag !~ /^val\d/ && build.tag !~ /^seed/
    name: ":whale: AMD64 docker"
    env:
      REGISTRY_HOST: "quay.io"
      REGISTRY_NAME: "miner"
      IMAGE_ARCH: "amd64"
      BUILD_TYPE: "miner"
    agents:
      queue: "erlang"
    commands:
      - "git fetch -t"
      - ".buildkite/scripts/make_image.sh"

  - if: build.tag != null && build.tag !~ /^validator/ && build.tag !~ /^val\d/ && build.tag !~ /^seed/
    name: ":whale: ARM64 docker"
    agents:
      queue: "arm64"
    env:
      REGISTRY_HOST: "quay.io"
      REGISTRY_NAME: "miner"
      IMAGE_ARCH: "arm64"
      BUILD_TYPE: "miner"
    commands:
      - "git fetch -t"
      - ".buildkite/scripts/make_image.sh"
