steps:
  - commands:
      - "make compile"
      - "make ci"
    name: ":hammer: build"
    key: "tests"
    agents:
      queue: "erlang"
    artifact_paths:
      - "artifacts/*"

  - if: build.tag =~ /^validator/
    name: ":debian: build validator deb"
    env:
      VERSION_TAG: $BUILDKITE_TAG
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_deb.sh"
    key: "deb"
    artifact_paths: "*.deb"
    # depends_on: "tests"  # can't do this right now with the test status as it is.
    agents:
      queue: "erlang"

  - if: build.tag =~ /^validator/
    name: ":cloud: upload validator deb to packagecloud"
    env:
      VERSION_TAG: $BUILDKITE_TAG
    commands:
      - ".buildkite/scripts/packagecloud_upload.sh"
    depends_on: "deb"
    agents:
      queue: "erlang"

  - if: build.tag =~ /^validator/
    name: "validator AMD64 docker"
    env:
      BUILD_TYPE: "validator"
      IMAGE_ARCH: "amd64"
      REGISTRY_HOST: "quay.io"
      REGISTRY_ORG: "team-helium"
      REGISTRY_NAME: "validator"
      VERSION_TAG: $BUILDKITE_TAG
      BUILD_NET: "mainnet"
    agents:
      queue: "erlang"
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_image.sh"

  - if: build.tag =~ /^validator/
    name: "validator ARM64 docker"
    env:
      BUILD_TYPE: "validator"
      IMAGE_ARCH: "arm64"
      REGISTRY_HOST: "quay.io"
      REGISTRY_ORG: "team-helium"
      REGISTRY_NAME: "validator"
      VERSION_TAG: $BUILDKITE_TAG
      BUILD_NET: "mainnet"
    agents:
      queue: "arm64"
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_image.sh"

  - if: build.tag =~ /^val\d/
    name: "testnet validator AMD64 docker"
    env:
      BUILD_TYPE: "val"
      IMAGE_ARCH: "amd64"
      REGISTRY_HOST: "quay.io"
      REGISTRY_ORG: "team-helium"
      REGISTRY_NAME: "validator"
      VERSION_TAG: $BUILDKITE_TAG
      BUILD_NET: "testnet"
    agents:
      queue: "erlang"
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_image.sh"

  - if: build.tag =~ /^val\d/
    name: "testnet validator ARM64 docker"
    env:
      BUILD_TYPE: "val"
      IMAGE_ARCH: "arm64"
      REGISTRY_HOST: "quay.io"
      REGISTRY_ORG: "team-helium"
      REGISTRY_NAME: "validator"
      VERSION_TAG: $BUILDKITE_TAG
      BUILD_NET: "testnet"
    agents:
      queue: "arm64"
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_image.sh"

  - if: build.tag != null && build.tag !~ /^validator/ && build.tag !~ /^val\d/
    name: ":whale: AMD64 docker"
    env:
      BUILD_TYPE: "miner"
      IMAGE_ARCH: "amd64"
      REGISTRY_HOST: "quay.io"
      REGISTRY_ORG: "team-helium"
      REGISTRY_NAME: "miner"
      VERSION_TAG: $BUILDKITE_TAG
      BUILD_NET: "mainnet"
    agents:
      queue: "erlang"
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_image.sh"

  - if: build.tag != null && build.tag !~ /^validator/ && build.tag !~ /^val\d/
    name: ":whale: ARM64 docker"
    agents:
      queue: "arm64"
    env:
      BUILD_TYPE: "miner"
      IMAGE_ARCH: "arm64"
      REGISTRY_HOST: "quay.io"
      REGISTRY_ORG: "team-helium"
      REGISTRY_NAME: "miner"
      VERSION_TAG: $BUILDKITE_TAG
      BUILD_NET: "mainnet"
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_image.sh"
