#!/bin/sh
if [ -t 0 ] ; then
    CLIQUE_COLUMNS=$(stty size 2>/dev/null | cut -d ' ' -f 2)
    export CLIQUE_COLUMNS
fi

j=1
l=$#
buf="[[\"genesis\","
while [ $j -le $l ]; do
    buf="$buf\"$1\","
    j=$(( j + 1 ))
    shift
done

buf="${buf%?}]]"

relx_nodetool rpc blockchain_console command "$buf"
exit $?
