#!/bin/sh

CONFIG=$(find $ROOTDIR/releases -name sys.config)
LIB_DIR=$ROOTDIR/lib

exec $BINDIR/$PROGNAME erl -pa $LIB_DIR/*/ebin -boot "$ROOTDIR/bin/start_clean" -boot_var ERTS_LIB_DIR "$ERTS_LIB_DIR" -noshell -eval "miner_keys:print_keys(\"${CONFIG}\")" -eval 'init:stop()'
